
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    team: aap
  name: aap-alerts
  namespace: aap
spec:
  groups:
    - name: namespace aap
      rules:
        - alert: namespace aap - Høy error rate i logger
          expr: (100 * sum by (app, namespace) (rate(logd_messages_total{log_level="Error",namespace="aap"}[3m])) / sum by (app, namespace) (rate(logd_messages_total{namespace="aap"}[3m]))) > 90
          for: 3m
          labels:
            severity: critical
            namespace: aap
            receiver_reference: "team-aap-alerts"
            alert_type: custom
          annotations:
            summary: Sjekk loggene til app {{ $labels.app }} i namespace {{ $labels.namespace }}, for å se hvorfor det er så mye feil
        - alert:  namespace aap - Stor mengde 5xx feil siste 10 minutter
          expr: (100 * (sum by (service, namespace) (rate(nginx_ingress_controller_requests{namespace="aap",status=~"^5\\d\\d",app!~"linkerd-proxy"}[3m]))/sum by (service, namespace) (rate(nginx_ingress_controller_requests{namespace="aap",app!~"linkerd-proxy"}[3m])))) > 10
          for: 10m
          labels:
            severity: critical
            namespace: aap
            receiver_reference: "team-aap-alerts"
            alert_type: custom
          annotations:
            summary: "`{{ $labels.deployment }}` har mange 5xx-feil siste"
        - alert:  Innsending - Journalføringer feiler
          expr: sum(increase(innsending_total{resultat="feilet"}[1h])) > 1
          for: 10m
          labels:
            severity: critical
            namespace: aap
            receiver_reference: "team-aap-alerts"
            alert_type: custom
          annotations:
            summary: "En eller flere journalføringer har feilet siste time. Sjekk navikt/aap-innsending"
        - alert:  Innsending - Lite journalføringer
          expr: sum(increase(innsending_total{resultat="ok"}[15m])) < 100
          for: 10m
          labels:
            severity: critical
            namespace: aap
            receiver_reference: "team-aap-alerts"
            alert_type: custom
          annotations:
            summary: "OBS: Dette er en test! Færre enn 10 journalføringer siste 4 timer. Sjekk navikt/aap-innsending"
